#!/usr/bin/env python3
# Author: Daniel Rode
# Created: 08 Apr 2024
# Updated: -


import sys
import pyproj
from shapely.geometry import Point
from shapely.ops import transform


args = sys.argv[1:]
try:
  in_point = Point(args[0], args[1])
  in_epsg = pyproj.CRS(f"EPSG:{args[2]}")
  out_epsg = pyproj.CRS(f"EPSG:{args[3]}")
except IndexError:
  print("Usage: this_script X Y IN_EPSG OUT_EPSG")
  exit(1)


transformation = pyproj.Transformer.from_crs(
  in_epsg, out_epsg, always_xy=True
).transform
out_point = transform(transformation, in_point)

print(out_point)
