#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Author: Daniel Rode
# Dependencies:
#   gdal
# Init: 29 Sep 2023
# Updated: 03 Nov 2023


# sudo apt install python3-gdal


import sys
from sys import exit

from osgeo import ogr


gpkg_pths = sys.argv[1:]
if len(gpkg_pths) < 1:
    print("Usage: lenf GPKG_PATH...")
    exit(1)


for pth in gpkg_pths:
    print(pth)
    for layer in ogr.GetDriverByName('GPKG').Open(pth, 0):
        print(f"{layer.GetName()}: {layer.GetFeatureCount()}")

