#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Author: Daniel Rode
# Dependencies:
#   gdal
#   column (Linux command)
# Created: 28 Sep 2023
# Updated: 04 Nov 2024


import sys
from sys import exit

import pyogrio
import subprocess as sp


HELP_TEXT = "Usage: lscols GPKG"


# Functions
def column_print(text):
    sp.run(['column'], input=text, text=True)


# Parse command line arguments
args = sys.argv[1:]
try:
    IN_PATH = args[0]
except IndexError:
    print(HELP_TEXT)
    exit(1)

# Find and print field names from spatial data set
info = pyogrio.read_info(IN_PATH)
for f in info["fields"]:
    print(f)
