#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Author: Daniel Rode
# Dependencies:
#   gdal
#   column (Linux command)
# Created: 28 Sep 2023
# Updated: 20 Dec 2023


# sudo apt install python3-gdal


import subprocess as sp
import sys
from sys import exit

from osgeo import ogr


# Functions
def column_print(text):
    sp.run(['column'], input=text, text=True)


# Main
spat_dat_pth_list = sys.argv[1:]  # List of spatial data file paths
for spat_dat_pth in spat_dat_pth_list:
    drivers = ('ESRI Shapefile', 'GPKG')
    for d in drivers:
        spat_dat = ogr.GetDriverByName(d).Open(spat_dat_pth, 0)
        if spat_dat:
            break

    for layer in spat_dat:
        print(f"{spat_dat_pth}//{layer.GetName()}:")
        ldef = layer.GetLayerDefn()
        field_names = []
        for i in range(ldef.GetFieldCount()):
            field_names.append(ldef.GetFieldDefn(i).GetName())

        column_print("\n".join(field_names))

