#!/usr/bin/env python3
# Author: Daniel Rode
# Dependencies:
#   GDAL
# Created: 23 May 2024
# Updated: -


import sys
from sys import exit
from pathlib import Path

import numpy as np

from osgeo import gdal
gdal.UseExceptions()


# Parse command line arguments
args = sys.argv[1:]
try:
  tif_pth = Path(args[0])
except IndexError:
  print("Usage: this-script TIFF_PATH [BAND_NUM]")
  exit(1)

if not tif_pth.is_file():
  print("error: File not found:", tif_pth)
  exit(1)

try:
  band = args[1]
except IndexError:
  band = 1


# Main
ds = gdal.Open(tif_pth)
arr = np.array(ds.GetRasterBand(band).ReadAsArray())
print(arr)
