#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Author: Daniel Rode


"""Clip raster and set NAs to zero.

Load a raster and clip it to a given polygon. Set all NA pixels
within the polygon to zero.
"""

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Import libraries
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# Import standard libraries
import sys
from pathlib import Path

# Import in-house libraries
from vogeler.stdlib import print2
from vogeler.stdlib import init_logger

# Import external libraries
import pyogrio
import numpy as np
import rasterio as rio
from rasterio.mask import mask as rio_mask


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Constants
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

EXE_NAME = sys.argv[0].split('/')[-1]  # This script's filename

# Text printed when user calls this script without proper parameters
HELP_TEXT = f"""Usage: {EXE_NAME}  SHP_PATH  TIF_PATH  OUT_TIF_PATH"""


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

def main() -> None:
    # Parse command line arguments
    args = sys.argv[1:]
    try:
        shp_path = Path(args[0])
        src_tif_path = Path(args[1])
        dst_tif_path = Path(args[2])
    except IndexError:
        print2(HELP_TEXT)
        sys.exit(1)

    for p in (shp_path, src_tif_path):
        if not p.exists():
            print2("error: Path does not exist: ", p)
            sys.exit(1)

    # Setup logging
    global log
    log = init_logger()

    # Load boundary
    log.info("Loading bounds...")
    bounds = pyogrio.read_dataframe(shp_path)

    # Clip and set NA pixels that fall inside the boundary to 0
    with rio.open(src_tif_path, 'r') as src_tif:
        # Load source raster
        log.info("Loading source TIFF...")
        arr = src_tif.read(1)

        # Set all raster NA values to zero
        log.info("Setting inside NAs to zero...")
        arr[np.isnan(arr)] = 0

        # Find portions of raster array that fall outside given shape boundary
        log.info("Clipping to bounds...")
        mask = rio_mask(
            src_tif, bounds.to_crs(src_tif.crs)['geometry'],
            crop=False, all_touched=True, filled=False, nodata=np.nan,
        )[0].mask[0]

        # Set all values that fall outside the boundary to NA
        arr[mask] = np.nan

        # Save new raster to file
        log.info("Saving: %s", dst_tif_path)
        with rio.open(dst_tif_path, 'w', **src_tif.profile) as dst:
            dst.write(arr, 1)

    log.info("Finished")


if __name__ == '__main__':
    main()
